#!/usr/bin/env node

/**
 * StaffForge auto-init — self-healing OpenCode configuration.
 *
 * Ensures the project's `opencode.json` declares the Orchestrator as the
 * default agent (mode: primary). If the file is healthy, exits silently.
 * If missing or stale (e.g. generated by a pre-2.7.3 installer), regenerates
 * it by delegating to packages/cli/install.mjs — the same installer used by
 * `npm run setup`, so behavior stays consistent.
 *
 * Non-destructive: never touches a valid config. After regeneration, restart
 * OpenCode (config is read at startup — there is no hot reload).
 *
 * Usage:
 *   npm run auto-init
 *   npx --yes @staffforge/staffforge-ai-agent-framework auto-init
 */

import { spawn } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const CWD = process.cwd();

const OPCODE_SCHEMA = 'https://opencode.ai/config.json';

function isHealthy() {
  const cfgPath = join(CWD, 'opencode.json');
  if (!existsSync(cfgPath)) return false;
  let cfg;
  try {
    cfg = JSON.parse(readFileSync(cfgPath, 'utf-8'));
  } catch {
    return false; // unparseable → stale
  }
  return (
    cfg?.$schema === OPCODE_SCHEMA &&
    cfg?.default_agent === 'orchestrator' &&
    typeof cfg?.agent?.orchestrator === 'object' &&
    cfg.agent.orchestrator.mode === 'primary'
  );
}

if (isHealthy()) {
  console.log('✓ opencode.json healthy (orchestrator is the default agent) — nothing to do.');
  process.exit(0);
}

console.log('… opencode.json missing or stale — regenerating with orchestrator as default agent …');
const installer = join(root, 'packages', 'cli', 'install.mjs');
if (!existsSync(installer)) {
  console.error(`✖ CLI installer not found at ${installer}`);
  process.exit(1);
}

const args = [installer, '--platform', 'opencode', '--agent', 'orchestrator', '--yes', '--force'];
const child = spawn(process.execPath, args, { stdio: 'inherit', cwd: CWD });
child.on('error', (err) => {
  console.error(`✖ auto-init failed to start installer: ${err.message}`);
  process.exit(1);
});
child.on('exit', (code) => {
  if (code === 0) {
    console.log('✓ opencode.json regenerated. Restart OpenCode to pick it up (no hot reload).');
  } else {
    console.error(`✖ auto-init failed (installer exit code ${code}).`);
  }
  process.exit(code ?? 1);
});
